import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import Header from "../components/Header";
import Footer from "../components/Footer";
import { Providers } from '@/components/Providers';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>

        <Providers >
            <Header />
            <main className='container'>
              {children}
            </main>
            <Footer />
        </Providers>

      </body>
    </html>
  )
}
